# Generated by Django 4.1.6 on 2023-02-06 15:38

from django.db import migrations
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        HStoreExtension(),
        migrations.RenameField(
            model_name='company',
            old_name='sub_domain',
            new_name='sub_domains',
        ),
    ]
