# Generated by Django 4.1.6 on 2023-02-06 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_sub_domain_company_sub_domains'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
    ]
