# Generated by Django 4.1.6 on 2023-02-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_company_address_company_contact_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='schema_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
