# Generated by Django 4.1.6 on 2023-02-06 20:05

import django.contrib.postgres.fields.hstore
from django.contrib.postgres.operations import HStoreExtension
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('address', django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
